### ISSUE TITLE
请求lolicon图库报错

### ISSUE THREAD

**Issue by Morturi** [Alex1911-Jiang/GreenOnions#14]
yande.re图库正常，请求到lolicon图库直接停止工作
发生异常:
    错误信息:The SSL connection could not be established, see inner exception.
    完整异常信息:System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): 接收到的消息异常，或格式不正确。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at GreenOnions.Utility.Helper.HttpHelper.GetHttpResponseStringAsync(String url, IDictionary`2 headers)
    线程ID:0    2022-12-18 13:35:40.6253
看上去是ssl证书问题，lolicon api证书到期了?
https://stackoverflow.com/questions/12553277/allowing-untrusted-ssl-certificates-with-httpclient

**Comment by Alex1911-Jiang** [comment]
不需要证书，如果是轻量应用服务器的话就寄了，如果是自己电脑的话可以进网络设置里把“随机硬件地址”关掉试试。
另外你可以试试装一下 [GreenOnions.CustomHttpApiInvoker.zip](https://github.com/Alex1911-Jiang/GreenOnions.Plugins/releases/download/2022.12.15/GreenOnions.CustomHttpApiInvoker.zip) 这个插件，在这里面填地址调一下lolicon图库看看成不成功，如果不成功话开启浏览器匿名（来宾）模式，用浏览器访问一下lolicon的api并把header信息填入插件中看看能否成功

**Comment by Alex1911-Jiang** [comment]
破案了，是 Windows Server 2012 R2 不支持 TLS 1.3 协议，新版里我加了个使用浏览器进行请求，就可以用了（隔壁picsearcher也是这样做的）
